<a href="https://colab.research.google.com/github/codedosecodes/python/blob/main/Python_mod05_Databases.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<img src="https://static.wixstatic.com/media/187085_663a141abb41479db38c836ad13ba2b8~mv2.png" alt="" width="200px" align="right"/>

# **Working with Files and Databases**

# Learn the Basics


Authors:
[Gabriel Mauricio Cortés](https://github.com/codedosecodes/),

<style>
.alert2 {
  padding: 20px;
  background-color: #f44336;
  color: white;
  margin-bottom: 15px;
}
.alert {
  border-radius: 10px;
  background-color: #bbb;
  border: 2px solid #999;
  margin-top: 20px;
  margin-bottom: 20px;
  padding-left: 5px;
  padding-top: 10px;
  padding-bottom: 10px;
  font-family: 'Arial', sans-serif;
}

.alert > h3 {
  display: block;
  font-size: 30px;
  margin-top: 5px;
  margin-bottom: 15px;
}

.alert-info {
  background-color: #1af !important;
  border: 2px solid #04a !important;
}
div.warn {    
    background-color: #fcf2f2;
    border-color: #dFb5b4;
    border-left: 5px solid #dfb5b4;
    padding: 0.5em;
    }
</style>


<table class="table table-bordered" style="border-color:green;" align="left">
  <td>
    <a target="_blank" href="https://www.codedose.codes/"><img src="https://static.wixstatic.com/media/187085_663a141abb41479db38c836ad13ba2b8~mv2.png" width="32" height="32" />View Codedose</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1SF6ZSh5SEjVczxJzfo5-Kcn9YdqxZhMI#scrollTo=8yVdUDBbkTF-"><img src="https://static.wixstatic.com/media/187085_adc0ad8b754748b5b46b2ce17d6c48fb~mv2.png" width="32" height="32" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/codedosecodes/python"><img src="https://static.wixstatic.com/media/187085_a8a39d79788e40ec8c2a70d4f42ec0ec~mv2.png" width="32" height="32" />View code in GitHub</a>
  </td>
  <td>
    <a href="https://drive.google.com/file/d/1bDXM7D3-magDiasoOTiE5YaPQw499jmi/view?usp=sharing"><img src="https://static.wixstatic.com/media/187085_dbe5b3fa6ced40fb83d52e0f38da647e~mv2.png" width="32" height="32" />Download notebook</a>
  </td>
        <td>
    <a target="_blank" href="https://nbviewer.org/github/codedosecodes/python/blob/main/Python_mod05_Databases.ipynb"><img src="https://static.wixstatic.com/media/187085_f270d64e2bdf462c9e26477d53a86602~mv2.png" width="32" height="32" />Jupyter Notebook</a>
  </td>
    <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1SF6ZSh5SEjVczxJzfo5-Kcn9YdqxZhMI#scrollTo=8yVdUDBbkTF-"><img src="https://static.wixstatic.com/media/187085_27f04669f65449f39f6b40b6a5945496~mv2.png" width="32" height="32" />View Video</a>
  </td>
</table>



<a ><img src="https://static.wixstatic.com/media/187085_df689c60bdf64324bab0e8bef9ea3db6~mv2.png" width="100%" height="100%" /></a>

Working with Files and Databases: Python libraries for working with files and databases, such as SQLite and SQLAlchemy, are introduced


## Objetives
### know and drive
1. SQLite
2. SQLAlchemy

All programs process data in one form or another, and many need to be able to save and retrieve that data from one invocation to the next. Python, SQLite, and SQLAlchemy give your programs database functionality, allowing you to store data in a single file without the need for a database server.

You can achieve similar results using flat files in any number of formats, including CSV, JSON, XML, and even custom formats. Flat files are often human-readable text files—though they can also be binary data—with a structure that can be parsed by a computer program. Below, you’ll explore using SQL databases and flat files for data storage and manipulation and learn how to decide which approach is right for your program.

Relational databases provide a way to store structured data in tables and establish relationships between those tables. They usually use Structured Query Language (SQL) as the primary way to interact with the data. This is an oversimplification of what RDBMSs provide, but it’s sufficient for the purposes of this tutorial.

An SQLite database provides support for interacting with the data table using SQL. Not only does an SQLite database file contain the data, but it also has a standardized way to interact with the data. This support is embedded in the file, meaning that any programming language that can use an SQLite file can also use SQL to work with it.

### Interacting With a Database With SQL
SQL is a declarative language used to create, manage, and query the data contained in a database. A declarative language describes what is to be accomplished rather than how it should be accomplished. You’ll see examples of SQL statements later when you get to creating database tables.

### Structuring a Database With SQL
To take advantage of the power in SQL, you’ll need to apply some database normalization to the data in the author_book_publisher.csv file. To do this, you’ll separate the authors, books, and publishers into separate database tables.

Conceptually, data is stored in the database in two-dimensional table structures. Each table consists of rows of records, and each record consists of columns, or fields, containing data.

The data contained in the fields is of pre-defined types, including text, integers, floats, and more. CSV files are different because all the fields are text and must be parsed by a program to have a data type assigned to them.

Each record in the table has a primary key defined to give a record a unique identifier. The primary key is similar to the key in a Python dictionary. The database engine itself often generates the primary key as an incrementing integer value for every record inserted into the database table.

Though the primary key is often automatically generated by the database engine, it doesn’t have to be. If the data stored in a field is unique across all other data in the table in that field, then it can be the primary key. For example, a table containing data about books could use the book’s ISBN as the primary key.

In [ ]:
## dowlload from google drive

#   from google.colab import drive
#   drive.mount('/content/drive')

## download from urls using file handling


# Database chinook.db
#   https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_38726ce1942a4c228180c005a08b2ba4.txt
# database begin SQLite.sql scripts
#   https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_a067705a5e52432b8a89b851b43db59a.txt
# Database base database.db
#   https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_97c4a2c2d24646558f472749a37fd706.txt
# database journal database.d-journal
#   https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_f619e0ec791d4a40ab688960eee75ccb.txt


import requests

# Database chinook.db
url = 'https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_38726ce1942a4c228180c005a08b2ba4.txt'
r = requests.get(url, allow_redirects=True)
open('chinook.db', 'wb').write(r.content)

# database begin SQLite.sql scripts
url = 'https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_a067705a5e52432b8a89b851b43db59a.txt'
r = requests.get(url, allow_redirects=True)
open('SQLite.sql', 'wb').write(r.content)


# database begin SQLite.sql scripts
url = 'https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_97c4a2c2d24646558f472749a37fd706.txt'
r = requests.get(url, allow_redirects=True)
open('database.db', 'wb').write(r.content)

# database begin SQLite.sql scripts
url = 'https://1870859c-e43a-48f9-b690-7af5dd055580.usrfiles.com/ugd/187085_f619e0ec791d4a40ab688960eee75ccb.txt'
r = requests.get(url, allow_redirects=True)
open('database.db-journal', 'wb').write(r.content)

4616


# 1. SQLite
SQLite is probably the most straightforward database to connect to with a Python application since you don’t need to install any external Python SQL modules to do so. By default, your Python installation contains a Python SQL library named sqlite3 that you can use to interact with an SQLite database.

What’s more, SQLite databases are serverless and self-contained, since they read and write data to a file. This means that, unlike with MySQL and PostgreSQL, you don’t even need to install and run an SQLite server to perform database operations!

### Features of SQLite
Let’s look at the key features of SQLite in Python:

| Feature |  Description |
| :--- | :--- |
| Self-contained: | SQLite is a self-contained, serverless database engine that runs within your application. This means that you don’t need to install any additional software or set up a separate server process to use it.
| Cross-platform: | SQLite is a cross-platform database engine that can run on various operating systems, including Windows, macOS, Linux, and many more.
|Lightweight:| SQLite is designed to be lightweight and fast, making it a great choice for small to medium-sized databases that don’t require a lot of concurrency or scalability.
| Full-featured:| Despite its lightweight design, SQLite is a full-featured relational database that supports many of the standard SQL features you expect from a relational database, including transactions, indexes, and views.
|Small footprint: |SQLite has a very small footprint, with the entire database engine contained within a single library file that can be embedded in your application.
| ACID-compliant:| SQLite is ACID-compliant, which means that it ensures data consistency and integrity even in the face of hardware or software failures.
|High performance: |SQLite is known for its high performance, thanks to its efficient design and memory-mapped I/O use.
|Scalable: |While SQLite is not designed for high-concurrency or high-scalability applications, it can still scale to support larger databases using techniques such as sharding or replication.
|Well-documented:| SQLite is very well-documented, with a comprehensive user manual covering all database engine aspects. There’s also a large and active community of developers who use and contribute to SQLite, meaning you can find plenty of resources and support if needed.
|Free and open-source:| SQLite is free and open-source software released under the public domain or permissive licenses, which means that you can use it for any purpose without needing to pay for a license or worry about vendor lock-in.



<a><img src="https://static.wixstatic.com/media/187085_2df67ffb258c4fb0a4bb78ac2cb8f8d5~mv2.png" width="80%" height="80%" /></a>

### Using database example

>  Reference: this model database from https://www.kaggle.com/code/alaasedeeq/chinook-sql/notebook

### Building Relationships
Another feature of database systems that you might find even more powerful and useful than data persistence and retrieval is relationships. Databases that support relationships allow you to break up data into multiple tables and establish connections between them.

### Entity Relationship Diagrams
An entity-relationship diagram (ERD) is a visual depiction of an entity-relationship model for a database or part of a database

This diagram presents the table structures in the database and the relationships between them. Each box represents a table and contains the fields defined in the table, with the primary key indicated first if it exists.

The arrows show the relationships between the tables connecting a foreign key field in one table to a field, often the primary key, in another table




<a ><img src="https://static.wixstatic.com/media/187085_1b68738efa7f4895bf188448e8e479bd~mv2.png" width="100%" height="100%" /></a>

### Case Sensitivity
The important point to be noted is that SQLite is case insensitive, i.e. the clauses GLOB and glob have the same meaning in SQLite statements.

### Comments
SQLite comments are extra notes, which you can add in your SQLite code to increase its readability and they can appear anywhere; whitespace can occur, including inside expressions and in the middle of other SQL statements but they cannot be nested.

SQL comments begin with two consecutive "-" characters (ASCII 0x2d) and extend up to and including the next newline character (ASCII 0x0a) or until the end of input, whichever comes first.

You can also use C-style comments, which begin with "/*" and extend up to and including the next "*/" character pair or until the end of input, whichever comes first. C-style comments can span multiple lines.

In [ ]:
import pandas as pd
import sqlite3

# coonection google drive
#   conn = sqlite3.connect('/content/drive/MyDrive/codedose/chinook.db', timeout=30)

conn = sqlite3.connect('/content/chinook.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,albums,albums,2,"CREATE TABLE ""albums""\r\n(\r\n [AlbumId] IN..."
1,table,sqlite_sequence,sqlite_sequence,3,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,artists,artists,4,"CREATE TABLE ""artists""\r\n(\r\n [ArtistId] ..."
3,table,customers,customers,5,"CREATE TABLE ""customers""\r\n(\r\n [Customer..."
4,table,employees,employees,8,"CREATE TABLE ""employees""\r\n(\r\n [Employee..."
5,table,genres,genres,10,"CREATE TABLE ""genres""\r\n(\r\n [GenreId] IN..."
6,table,invoices,invoices,11,"CREATE TABLE ""invoices""\r\n(\r\n [InvoiceId..."
7,table,invoice_items,invoice_items,13,"CREATE TABLE ""invoice_items""\r\n(\r\n [Invo..."
8,table,media_types,media_types,15,"CREATE TABLE ""media_types""\r\n(\r\n [MediaT..."
9,table,playlists,playlists,16,"CREATE TABLE ""playlists""\r\n(\r\n [Playlist..."
10,table,playlist_track,playlist_track,17,"CREATE TABLE ""playlist_track""\r\n(\r\n [Pla..."
11,table,tracks,tracks,20,"CREATE TABLE ""tracks""\r\n(\r\n [TrackId] IN..."
12,table,sqlite_stat1,sqlite_stat1,864,"CREATE TABLE sqlite_stat1(tbl,idx,stat)"

In [ ]:
album = sq('''select * from Albums''')
album.head(2)

   AlbumId                                  Title  ArtistId
0        1  For Those About To Rock We Salute You         1
1        2                      Balls to the Wall         2

In [ ]:
artist = sq('''select * from Artists''')
artist.head(2)

   ArtistId    Name
0         1   AC/DC
1         2  Accept

In [ ]:
customer = sq('''select * from Customers''')
customer.head(2)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5

In [ ]:
invoices= sq('''select * from invoices''')
invoices.head(2)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96

In [ ]:
conn.close()

## Step 1 — Setting up the Database
In this step, you’ll set up the SQLite database you’ll use to store your data. You’ll then populate the database with a few example entries.

You will use the sqlite3 module to interact with the database, which is readily available in the standard Python library.

Data in SQLite is stored in tables and columns, so you first need to create a table called posts with the necessary columns. You’ll create a .sql file that contains SQL commands to create the posts table with a few columns. You’ll then use this schema file to create the database.

Open a database schema file called SQLite.sql locate \content directory:

In this schema file, you first delete the posts table if it already exists. This avoids the possibility of another table named posts existing, which might result in confusing behavior (for example, if it has different columns). This isn’t the case here, because you haven’t created the table yet, so the SQL command won’t be executed. Note that this will delete all of the existing data whenever you execute this schema file. For our purposes, you will only execute this schema once, but you might want to execute it again to delete whatever data you inserted and start with an empty database again.

Next, you use CREATE TABLE posts to create the posts table

In [ ]:
conn.close()

In [ ]:
import sqlite3

# connection = sqlite3.connect('/content/drive/MyDrive/codedose/database.db', timeout=30)

connection = sqlite3.connect('/content/database.db', timeout=30)

# with open('/content/drive/MyDrive/codedose/SQLite.sql') as f:

with open('/content/SQLite.sql') as f:
    connection.executescript(f.read())

cur = connection.cursor()



connection.commit()
connection.close()

In [ ]:

# conn = sqlite3.connect('/content/drive/MyDrive/codedose/database.db', timeout=30)
conn = sqlite3.connect('/content/database.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql_query('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,"CREATE TABLE users (id INTEGER PRIMARY KEY, na..."
1,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,usersDB,usersDB,18,"CREATE TABLE usersDB (id INTEGER PRIMARY KEY, ..."
3,table,Student,Student,19,"CREATE TABLE ""Student"" (\n\t""Id"" INTEGER NOT N..."
4,table,Categories,Categories,3,CREATE TABLE Categories\n( \n Category...
5,table,Customers,Customers,5,CREATE TABLE Customers\n( \n CustomerI...
6,table,Employees,Employees,6,CREATE TABLE Employees\n(\n EmployeeID INTE...
7,table,Shippers,Shippers,7,CREATE TABLE Shippers(\n ShipperID INTEGER ...
8,table,Suppliers,Suppliers,8,CREATE TABLE Suppliers(\n SupplierID INTEGE...
9,table,Products,Products,9,CREATE TABLE Products(\n ProductID INTEGER ...
10,table,Orders,Orders,10,CREATE TABLE Orders(\n OrderID INTEGER PRIM...
11,table,OrderDetails,OrderDetails,11,CREATE TABLE OrderDetails(\n OrderDetailID ...

In [ ]:
conn.close()

### Creating Tables With SQL
Here’s how you can create the three tables representing users

In [ ]:
import sqlite3
from sqlite3 import Error

def create_connection(path):
    connection = None
    try:
        connection = sqlite3.connect(path)
        print("Connection to SQLite DB successful")
    except Error as e:
        print(f"The error '{e}' occurred")

    return connection

# create database
# conn = create_connection("/content/drive/MyDrive/codedose/database.db", timeout=30)
conn = create_connection("/content/database.db")
conn.execute('DROP TABLE usersDB')
conn.execute('CREATE TABLE usersDB (id INTEGER PRIMARY KEY, name TEXT, age INTEGER)')
conn.execute("INSERT INTO usersDB (name, age) VALUES ('Gabriel', 25)")
conn.execute("INSERT INTO usersDB (name, age) VALUES ('JUan', 30)")
conn.commit()

cursor = conn.execute('SELECT * FROM usersDB')

# Loop through the results and print them

for row in cursor:

    print(row)

# Close the connection

conn.close()

Connection to SQLite DB successful
(1, 'Gabriel', 25)
(2, 'JUan', 30)

In [ ]:
# conn = sqlite3.connect('/content/drive/MyDrive/codedose/database.db', timeout=30)
conn = sqlite3.connect('/content/database.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,"CREATE TABLE users (id INTEGER PRIMARY KEY, na..."
1,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,Student,Student,19,"CREATE TABLE ""Student"" (\n\t""Id"" INTEGER NOT N..."
3,table,Categories,Categories,3,CREATE TABLE Categories\n( \n Category...
4,table,Customers,Customers,5,CREATE TABLE Customers\n( \n CustomerI...
5,table,Employees,Employees,6,CREATE TABLE Employees\n(\n EmployeeID INTE...
6,table,Shippers,Shippers,7,CREATE TABLE Shippers(\n ShipperID INTEGER ...
7,table,Suppliers,Suppliers,8,CREATE TABLE Suppliers(\n SupplierID INTEGE...
8,table,Products,Products,9,CREATE TABLE Products(\n ProductID INTEGER ...
9,table,Orders,Orders,10,CREATE TABLE Orders(\n OrderID INTEGER PRIM...
10,table,OrderDetails,OrderDetails,11,CREATE TABLE OrderDetails(\n OrderDetailID ...
11,table,usersDB,usersDB,18,"CREATE TABLE usersDB (id INTEGER PRIMARY KEY, ..."

### The Current Working Directory
Every program that runs on your computer has a current working directory, or cwd. Any filenames or paths that do not begin with the root folder are assumed to be under the current working directory. You can get the current working directory as a string value with the os.getcwd() function and change it with os.chdir(). Enter the following into the interactive shell:

### Types of File
* Text File: Text file usually we use to store character data. For example, test.txt
* Binary File: The binary files are used to store binary data such as images, video files, audio files, etc.

### File Path
A file path defines the location of a file or folder in the computer system. There are two ways to specify a file path.

Absolute path: which always begins with the root folder
Relative path: which is relative to the program's current working directory
The absolute path includes the complete directory list required to locate the file.

For example, /user/codedose/data/sales.txt is an absolute path to discover the sales.txt. All of the information needed to find the file is contained in the path string.

After the filename, the part with a period(.) is called the file's extension, and that tells us the type of file. Here, project.pdf is a pdf document.

### Absolute Path vs Relative Path
Absolute Path is the hierarchical path that locates a file or folder in a file system starting from the root. The absolute path of a file enables the location of the file to be precisely specified, independent of where the user’s current directory is located.

In MS-DOS and Microsoft Windows platforms, the absolute path of a file is specified starting with a drive letter, followed by the hierarchy of directories in which the file is contained (with each directory separated by a backslash), and concluding with the exact filename.

There are two ways to specify a file path.

>* An absolute path, which always begins with the root folder
>* A relative path, which is relative to the program’s current working directory

There are also the dot (.) and dot-dot (..) folders. These are not real folders but special names that can be used in a path. A single period (“dot”) for a folder name is shorthand for “this directory.” Two periods (“dot-dot”) means “the parent folder.”

## Python SQLAlchemy
is a powerful and flexible Object-Relational Mapping (ORM) library that simplifies database interactions in Python applications. It provides developers with a high-level, Pythonic interface to interact with relational databases, allowing them to work with databases using Python classes and objects, rather than writing complex SQL queries and this way abstracting their code, removing any native syntax for all supported database systems, such as PostgreSQL, MySQL, SQLite, and Oracle.


<a><img src="https://static.wixstatic.com/media/187085_6b1b3d5fb4454f5baccbecf95bfecf77~mv2.png" width="80%" height="80%" /></a>

SQLAlchemy is a powerful database access tool kit for Python, with its object-relational mapper (ORM) being one of its most famous components, and the one discussed and used here.

When you’re working in an object-oriented language like Python, it’s often useful to think in terms of objects. It’s possible to map the results returned by SQL queries to objects, but doing so works against the grain of how the database works. Sticking with the scalar results provided by SQL works against the grain of how Python developers work. This problem is known as object-relational impedance mismatch.

The ORM provided by SQLAlchemy sits between the SQLite database and your Python program and transforms the data flow between the database engine and Python objects. SQLAlchemy allows you to think in terms of objects and still retain the powerful features of a database engine.

SQLAlchemy is a popular open-source SQL toolkit and Object-Relational Mapping (ORM) library for Python. It provides a set of high-level APIs and tools for interacting with relational databases such as MySQL, PostgreSQL, SQLite, Oracle, and Microsoft SQL Server. SQLAlchemy is designed to provide developers with a unified and consistent API for accessing different relational database systems.

Relational databases are a type of database that store data in a structured format, using tables with columns and rows to represent data entities. They are designed to ensure data consistency and provide powerful querying capabilities, making them popular for many types of applications, including web applications, finance, and e-commerce.

 SQLAlchemy, on the other hand, is a Python library that provides a higher-level interface for working with databases, including SQLite. It allows you to write Python code interacting with your database, making it easier to manipulate data and write complex queries.  

## Features of SQLAlchemy


| Feature |  Description |
| :--- | :--- |
|Object Relational Mapper (ORM): | SQLAlchemy’s ORM allows you to map Python classes to database tables and perform database operations using Python code. This makes it easy to work with databases in a more object-oriented way without needing to write raw SQL queries. |
|SQL expression language: | SQLAlchemy’s SQL expression language provides a way to write SQL queries in a more Pythonic way. This makes it easier to write complex queries, and it can also help to prevent SQL injection attacks. |
|Multiple database support: | SQLAlchemy supports a wide range of database backends, including PostgreSQL, MySQL, SQLite, and Oracle, among others. |
|Flexibility and control: | SQLAlchemy provides much flexibility and control over how you interact with databases. For example, you can use SQLAlchemy to create and manage database schema, handle database transactions, and execute raw SQL queries if needed. |
|Connection pooling: | SQLAlchemy includes built-in support for connection pooling, which can help improve database connection performance in multi-threaded or multi-process applications. |
|Optional extensions and plugins: | SQLAlchemy provides a wide range of optional extensions and plugins that can add additional functionality, such as support for full-text search or geographic data. |
|Cross-database compatibility: | SQLAlchemy supports a consistent API across different database backends, which makes it easier to switch between databases or use multiple databases in the same application.|


Here’s what each class and functions are responsible for:

| Function |  Description |
| :--- | :--- |
|create_engine:| This function is used to create an SQLAlchemy engine that connects to a database. It is the starting point for interacting with databases using SQLAlchemy and will be used to create an engine to connect to the SQLite database.
|ForeignKey:| This class provides a way to define foreign keys in SQLAlchemy classes. Foreign keys are used to establish relationships between tables in a relational database.
|Column: |This class is used to define columns in SQLAlchemy classes. Columns represent individual fields in a database table.
|String: |This class is used to define a string data type for SQLAlchemy columns.
|Integer: |This class is used to define an integer data type for SQLAlchemy columns.
|CHAR: |This class represents a character column in a database table.
|CheckConstraint:| This class defines a check constraint in a table, which is a condition that must be met for the data to be valid.
|join:| This function constructs a SQL join between two or more tables, which allows data from different tables to be combined in a single query result.

Once you have installed SQLAlchemy, you can import it into your Python script using the following code:
> from sqlalchemy import create_engine

In [ ]:
from sqlalchemy import create_engine, CHAR, CheckConstraint, join
from sqlalchemy import Column, Integer, String, ForeignKey, Table
from sqlalchemy.orm import relationship, backref,registry
from sqlalchemy import Table, Column, Integer, String, MetaData
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import select

Next, add the following line of code to import the declarative_base function from the sqlalchemy.ext.declarative module.

In [ ]:
from sqlalchemy.ext.declarative import declarative_base

💡 The declarative_base function is used to create a base class that is used to define the database schema. This base class allows us to define the database schema in a way that is more like defining regular Python classes, and it makes it easy to create new database tables and columns.

After creating the base class by using the declarative_base function, we can define classes that inherit from the base class, and each of these classes represents a table in the database. We can define the columns of the table as attributes of the class, and we can define relationships between tables using attributes as well. Once we have defined all of our classes, we can use SQLAlchemy to create the database schema and interact with the database using the classes we have defined.

Add the following line of code to import the sessionmaker class and the relationship function from the SQLAlchemy ORM (Object Relational Mapper) module.

In [ ]:
from sqlalchemy.orm import sessionmaker, relationship

These classes do the following;

1. sessionmaker: It is a factory class that returns a new Session class when called with a database engine. The Session class is used to create database sessions, which are used to communicate with the database and perform CRUD (Create, Read, Update, Delete) operations.
2. relationship: It is a function that is used to define relationships between two database tables. It is used to specify how data in one table is related to data in another table. The relationship function is used to create a bidirectional relationship between two database tables.

Finally, create a new instance of the declarative_base class provided by SQLAlchemy and assign it to the variable Base. This instance will be used as a base class for the definition of database models using the SQLAlchemy ORM (Object-Relational Mapping) framework.

In [ ]:
Base = declarative_base()

<ipython-input-62-9bae6e3862ba>:1: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

### Connecting to SQL Database using SQLAlchemy in Python

To connect to a SQL database using SQLAlchemy we will require the sqlalchemy library installed in our python environment

The create_engine() method of sqlalchemy library takes in the connection URL and returns a sqlalchemy engine that references both a Dialect and a Pool, which together interpret the DBAPI’s module functions as well as the behavior of the database.

**Example 1: For MySQL Database**


In this example,  we have successfully created a connection to the MySQL database. Please note that we have created the database named ‘GeekForGeeks’ in the local instance of mySQL server with the password set as ‘password’. The dialect and driver for establishing the connection to MySQL database are MySQL and pymysql respectively.

In [ ]:
# IMPORT THE SQALCHEMY LIBRARY's CREATE_ENGINE METHOD
from sqlalchemy import create_engine

# DEFINE THE DATABASE CREDENTIALS
user = 'root'
password = 'password'
host = '127.0.0.1'
port = 3306
database = 'GeeksForGeeks'

# PYTHON FUNCTION TO CONNECT TO THE MYSQL DATABASE AND
# RETURN THE SQLACHEMY ENGINE OBJECT
def get_connection():
	return create_engine(
		url="mysql+pymysql://{0}:{1}@{2}:{3}/{4}".format(
			user, password, host, port, database
		)
	)


if __name__ == '__main__':

	try:

		# GET THE CONNECTION OBJECT (ENGINE) FOR THE DATABASE
		engine = get_connection()
		print(
			f"Connection to the {host} for user {user} created successfully.")
	except Exception as ex:
		print("Connection could not be made due to the following error: \n", ex)

Connection could not be made due to the following error:
 No module named 'pymysql'

**Example 2: For PostgreSQL Database**

In this example, a sqlalchemy engine connection has been established with the PostgreSQL database. Please note that we have used the pre-existing database named ‘postgres’ that comes within the local instance of postgresql server. The dialect and driver for establishing the connection to MySQL database is postgres.

In [ ]:
# IMPORT THE SQALCHEMY LIBRARY's CREATE_ENGINE METHOD
from sqlalchemy import create_engine
import pandas as pd


# DEFINE THE DATABASE CREDENTIALS
user = 'root'
password = 'password'
host = '127.0.0.1'
port = 5432
database = 'postgres'

# PYTHON FUNCTION TO CONNECT TO THE POSTGRESQL DATABASE AND
# RETURN THE SQLACHEMY ENGINE OBJECT
def get_connection():
	return create_engine(
		url="postgresql://{0}:{1}@{2}:{3}/{4}".format(
			user, password, host, port, database
		)
	)


if __name__ == '__main__':

	try:
		# GET THE CONNECTION OBJECT (ENGINE) FOR THE DATABASE
		engine = get_connection()
		print(f"Connection to the {host} for user {user} created successfully.")



	except Exception as ex:
		print("Connection could not be made due to the following error: \n", ex)

Connection to the 127.0.0.1 for user root created successfully.

**Example 3: For SQLite3  Database**

In this example, a sqlalchemy engine connection has been established with the SQLite3  database. Please note that we have used the pre-existing database named ‘sqllite3’ that comes within the local instance of postgresql server. The dialect and driver for establishing the connection to MySQL database is postgres.

In [ ]:
# IMPORT THE SQALCHEMY LIBRARY's CREATE_ENGINE METHOD
from sqlalchemy import create_engine
import os
import pandas as pd
from sqlalchemy import text


#version 1
# app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:////content/drive/MyDrive/codedose/database.db'


# PYTHON FUNCTION TO CONNECT TO THE POSTGRESQL DATABASE AND
# RETURN THE SQLACHEMY ENGINE OBJECT
def get_connection():
	return  create_engine('sqlite:////content/database.db', connect_args={"timeout": 30}, echo=True)
 	# return  create_engine('sqlite:////content/drive/MyDrive/codedose/database.db', connect_args={"timeout": 30}, echo=True)



if __name__ == '__main__':

	try:
		# GET THE CONNECTION OBJECT (ENGINE) FOR THE DATABASE


		engine = get_connection()
		print(
			f"Connection to the {host} for user {user} created successfully.")
	except Exception as ex:
		print("Connection could not be made due to the following error: \n", ex)

print(os.getcwd())

Connection to the 127.0.0.1 for user root created successfully.
/content

In [ ]:
import pandas as pd
import sqlite3

# coonection google drive
#   conn = sqlite3.connect('/content/drive/MyDrive/codedose/chinook.db', timeout=30)

conn = sqlite3.connect('/content/database.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,"CREATE TABLE users (id INTEGER PRIMARY KEY, na..."
1,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,usersDB,usersDB,18,"CREATE TABLE usersDB (id INTEGER PRIMARY KEY, ..."
3,table,Student,Student,19,"CREATE TABLE ""Student"" (\n\t""Id"" INTEGER NOT N..."
4,table,Categories,Categories,3,CREATE TABLE Categories\n( \n Category...
5,table,Customers,Customers,5,CREATE TABLE Customers\n( \n CustomerI...
6,table,Employees,Employees,6,CREATE TABLE Employees\n(\n EmployeeID INTE...
7,table,Shippers,Shippers,7,CREATE TABLE Shippers(\n ShipperID INTEGER ...
8,table,Suppliers,Suppliers,8,CREATE TABLE Suppliers(\n SupplierID INTEGE...
9,table,Products,Products,9,CREATE TABLE Products(\n ProductID INTEGER ...
10,table,Orders,Orders,10,CREATE TABLE Orders(\n OrderID INTEGER PRIM...
11,table,OrderDetails,OrderDetails,11,CREATE TABLE OrderDetails(\n OrderDetailID ...

> from sqlalchemy import create_engine

To connect to a database using SQLAlchemy, you first need to create an Engine object representing the underlying database connection. You can create an Engine object using the create_engine() function, like this:

### Connecting the database
We will be using the SQLite database from database.db, and it has one tables: usersDB.

First, we will create SQLite engine objects using ‘create_object’ and pass the location address of the database. Then, we will create a connection object by connecting the engine. We will use the ‘connection’ object to run all types of SQL queries.

In [ ]:
from sqlalchemy import create_engine
import sqlalchemy as db
# engine = db.create_engine('sqlite:////content/drive/MyDrive/codedose/database.db', connect_args={"timeout": 30},)
engine = db.create_engine('sqlite:////content/database.db', connect_args={"timeout": 30},)
connection = engine.connect()

In the example above, we are connecting to a SQLite database located in a file named database.db. The database URL follows the format dialect+driver://username:password@host:port/database.

Once the Engine is created, you can use it to interact with the database. In this tutorial, we will use the Engine to create tables and perform CRUD operations. Note that when you are finished working with the database, you should close the connection by calling the engine.dispose() method.

### Accessing the table
To create a table object, we need to provide table names and metadata. You can produce metadata using SQLAlchemy’s `MetaData()` function.

In [ ]:
from sqlalchemy import create_engine
import sqlalchemy as db
# engine = db.create_engine('sqlite:////content/drive/MyDrive/codedose/database.db', connect_args={"timeout": 30},)
engine = db.create_engine('sqlite:////content/database.db', connect_args={"timeout": 30},)
connection = engine.connect()


metadata = db.MetaData() #extracting the metadata
tableusers= db.Table('users', metadata,
autoload_with=engine) #Table object

users = sq('''select * from usersDB''')
users.head(2)

   id     name  age
0   1  Gabriel   25
1   2     JUan   30

In [ ]:
student = sq('''select * from Student''')
student.head(2)

Empty DataFrame
Columns: [Id, Name, Major, Pass]
Index: []

Let’s print the usersDB metadata.

> The metadata contains the table name, column names with the type, and schema.

In [ ]:
print(repr(metadata.tables['users']))

Table('users', MetaData(), Column('id', INTEGER(), table=<users>, primary_key=True), Column('name', TEXT(), table=<users>), Column('age', INTEGER(), table=<users>), schema=None)

Let’s use the table object “usersDB” to print column names.

In [ ]:
print(tableusers.columns.keys())

['id', 'name', 'age']

### Simple SQL query
Now comes the fun part. We will use the table object to run the query and extract the results.

In the code below, we are selecting all of the columns for the “usersDB” table.

In [ ]:

query = tableusers.select() #SELECT * FROM divisions
print(query)

SELECT users.id, users.name, users.age
FROM users

### SQL query result
We will now execute the query using the connection object and extract the first five rows.

* fetchone(): it will extract a single row at a time.
* fetchmany(n): it will extract the n number of rows at a time.
* fetchall(): it will extract all of the rows.

In [ ]:

exe = connection.execute(query) #executing the query
result = exe.fetchmany(5) #extracting top 5 results
print(result)

[(1, 'Gabriel', 25), (2, 'JUan', 30)]

In [ ]:
connection.close()

###Python SQLAlchemy Examples
In this section, we will look at various SQLAlchemy examples for creating tables, inserting values, running SQL queries, data analysis, and table management.

You can follow along or check out DataCamp’s Workspace. It contains a database, source code, and results.

### Creating Tables and Schema

To perform CRUD operations in SQLAlchemy, we first need to define the schema for our data. A schema is a blueprint that describes the structure of the data that will be stored in the database. In our stock ticker tracking application, we will need a table to store information about the stocks that we are tracking.

To define the schema for our table, we will use SQLAlchemy’s declarative_base class, which provides a base class for creating the schema of our tables. First, we need to import the class and create an instance of it:


We have created the structure of the table. Let’s add it to the database using `metadata.create_all(engine)`.

In [ ]:
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

<ipython-input-81-ec1eaaf05b90>:3: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [ ]:
import pandas as pd
import sqlite3

# coonection google drive
#   conn = sqlite3.connect('/content/drive/MyDrive/codedose/chinook.db', timeout=30)

conn = sqlite3.connect('/content/database.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,"CREATE TABLE users (id INTEGER PRIMARY KEY, na..."
1,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,usersDB,usersDB,18,"CREATE TABLE usersDB (id INTEGER PRIMARY KEY, ..."
3,table,Student,Student,19,"CREATE TABLE ""Student"" (\n\t""Id"" INTEGER NOT N..."
4,table,Categories,Categories,3,CREATE TABLE Categories\n( \n Category...
5,table,Customers,Customers,5,CREATE TABLE Customers\n( \n CustomerI...
6,table,Employees,Employees,6,CREATE TABLE Employees\n(\n EmployeeID INTE...
7,table,Shippers,Shippers,7,CREATE TABLE Shippers(\n ShipperID INTEGER ...
8,table,Suppliers,Suppliers,8,CREATE TABLE Suppliers(\n SupplierID INTEGE...
9,table,Products,Products,9,CREATE TABLE Products(\n ProductID INTEGER ...
10,table,Orders,Orders,10,CREATE TABLE Orders(\n OrderID INTEGER PRIM...
11,table,OrderDetails,OrderDetails,11,CREATE TABLE OrderDetails(\n OrderDetailID ...

In [ ]:
from sqlalchemy import Column, Integer, String, Sequence

class Stock(Base):
    __tablename__ = 'stocks'
    id = Column(Integer, primary_key=True)
    symbol = Column(String(10), unique=True, nullable=False)
    name = Column(String(100), nullable=False)
    price = Column(Integer, nullable=False)

    def __init__(self, symbol, name, price):
            self.symbol = symbol
            self.name = name
            self.price= price

In the example above, we have created a Stock class that represents a row in our stocks table. The __tablename__ attribute specifies the name of the table in the database. The id column is the primary key of the table and is defined as an Integer column. The symbol column is a unique identifier for the stock and is defined as a String column with a maximum length of 10 characters. The name and price columns are also defined as String and Integer columns, respectively.

Once we have defined our schema, we can create the table in the database by calling the Base.metadata.create_all() method and passing in the engine as an argument:

In [ ]:
Base.metadata.create_all(engine)

This method will create the stocks table in the database with the columns defined in the Stock class. Note that this method will only create the table if it does not already exist in the database.

In [ ]:
import pandas as pd
import sqlite3

# coonection google drive
#   conn = sqlite3.connect('/content/drive/MyDrive/codedose/chinook.db', timeout=30)

conn = sqlite3.connect('/content/database.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,"CREATE TABLE users (id INTEGER PRIMARY KEY, na..."
1,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,usersDB,usersDB,18,"CREATE TABLE usersDB (id INTEGER PRIMARY KEY, ..."
3,table,Student,Student,19,"CREATE TABLE ""Student"" (\n\t""Id"" INTEGER NOT N..."
4,table,Categories,Categories,3,CREATE TABLE Categories\n( \n Category...
5,table,Customers,Customers,5,CREATE TABLE Customers\n( \n CustomerI...
6,table,Employees,Employees,6,CREATE TABLE Employees\n(\n EmployeeID INTE...
7,table,Shippers,Shippers,7,CREATE TABLE Shippers(\n ShipperID INTEGER ...
8,table,Suppliers,Suppliers,8,CREATE TABLE Suppliers(\n SupplierID INTEGE...
9,table,Products,Products,9,CREATE TABLE Products(\n ProductID INTEGER ...
10,table,Orders,Orders,10,CREATE TABLE Orders(\n OrderID INTEGER PRIM...
11,table,OrderDetails,OrderDetails,11,CREATE TABLE OrderDetails(\n OrderDetailID ...
12,table,stocks,stocks,20,"CREATE TABLE stocks (\n\tid INTEGER NOT NULL, ..."

### Inserting Data into a Table
Now that we have created our stocks table, we can start inserting data into it. To insert data, we first need to create a session. A session is a communication channel between our application and the database, and it is used to manage the transactions that we perform on the database. To create a session, we use the sessionmaker class from SQLAlchemy’s orm module:

In [ ]:
from sqlalchemy.orm import sessionmaker

Session = sessionmaker(bind=engine)
session = Session()

In the example above, we have created a Session class that is bound to the engine that we created in the previous step. We then create an instance of the Session class, which gives us a session that we can use to perform transactions on the database.

Once we have a session, we can insert data into the stocks table by creating instances of the Stock class and adding them to the session using the session.add() method:

In [ ]:
stock = Stock(symbol='AAPL', name='Apple Inc.', price=120)
session.add(stock)
session.commit()

In the example above, we have created a Stock object and added it to the session. The session.commit() method is then called to commit the transaction, which writes the data to the database. Note that if you make multiple changes to the database in the same session, you only need to call the session.commit() method once to commit all of the changes.

You can insert multiple Stock objects into the stocks table by adding them to the session and calling the session.commit() method once:

In [ ]:
stocks = session.query(Stock.name, Stock.price).all()
for stock in stocks:
    print(stocks)

[('Apple Inc.', 120)]

In [ ]:
stock1 = Stock(symbol='GOOG', name='Alphabet Inc.', price=1100)
stock2 = Stock(symbol='MSFT', name='Microsoft Corporation', price=200)


session.add_all([stock1, stock2])
session.commit()

In the example above, we have inserted two Stock objects into the stocks table by adding them to the session and calling the session.commit() method.

In [ ]:
stocks = session.query(Stock.name, Stock.price).all()
for stock in stocks:
    print(stocks)

[('Apple Inc.', 120), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Apple Inc.', 120), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Apple Inc.', 120), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]

### Retrieving Data from a Table
Once we have inserted data into the stocks table, we can retrieve it by performing a query on the table. To perform a query, we use the session.query() method and chain it with other methods to specify the criteria for the query.

For example, to retrieve all rows from the stocks table, we can use the following code:

In [ ]:

stocks = session.query(Stock.name).all()
for stock in stocks:
    print(stocks)

[('Apple Inc.',), ('Alphabet Inc.',), ('Microsoft Corporation',)]
[('Apple Inc.',), ('Alphabet Inc.',), ('Microsoft Corporation',)]
[('Apple Inc.',), ('Alphabet Inc.',), ('Microsoft Corporation',)]

The session.query(Stock) method creates a query that retrieves all columns from the Stock class, and the .all() method retrieves all of the rows from the stocks table that match the criteria specified by the query. The result of the query is stored in the stocks variable, which is a list of Stock objects.

To retrieve a specific row from the stocks table, we can use the .filter() method to specify a filter criteria for the query. For example, to retrieve a row with a specific symbol value, we can use the following code:

In [ ]:


stocks = session.query( Stock.id,Stock.symbol, Stock.name, Stock.price).filter( Stock.name.like('%Micro%'),
        Stock.price == 200).all()
for stock in stocks:
    print(stocks)

[(3, 'MSFT', 'Microsoft Corporation', 200)]

In the example above, we have specified a filter criteria of Stock.symbol == 'AAPL', which returns the first row from the stocks table where the symbol column is equal to 'AAPL'. The result of the query is stored in the stock variable, which is a Stock object.

We can also retrieve specific columns from the stocks table by specifying them in the query() method. For example, to retrieve only the name and price columns for all rows in the stocks table, we can use the following code:

In [ ]:
stocks = session.query(Stock.name, Stock.price).all()
for stock in stocks:
    print(stocks)

[('Apple Inc.', 120), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Apple Inc.', 120), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Apple Inc.', 120), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]

In [ ]:
stock = sq('''select * from stocks''')
stock.head(2)

   id symbol           name  price
0   1   AAPL     Apple Inc.    120
1   2   GOOG  Alphabet Inc.   1100

In the example above, we have specified the Stock.name and Stock.price columns in the query() method, which returns a list of tuples where each tuple contains the name and price values for a row in the stocks table.

### Updating Data in a Table
To update data in a table, we first need to retrieve the row that we want to update, make the changes to the data, and then commit the changes to the database.

For example, to update the price of a stock with a specific symbol, we can use the following code:

In [ ]:
stock = session.query(Stock).filter(Stock.symbol == 'AAPL').first()
stock.price = 130
session.commit()

n the example above, we have retrieved the Stock object for the stock with the symbol value of 'AAPL', made the change to the price value, and then committed the changes to the database by calling the session.commit() method.

Note that when you make changes to a row in a table, you must always call the session.commit() method to commit the changes to the database. If you do not call the session.commit() method, the changes will be lost when the session is closed.

In [ ]:
stocks = session.query(Stock.name, Stock.price).all()
for stock in stocks:
    print(stocks)

[('Apple Inc.', 130), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Apple Inc.', 130), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Apple Inc.', 130), ('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]

### Deleting Data from a Table
To delete data from a table, we first need to retrieve the row that we want to delete, and then call the session.delete() method on the object, followed by calling session.commit() to commit the changes to the database.

For example, to delete a stock with a specific symbol, we can use the following code:

In [ ]:
stock = session.query(Stock).filter(Stock.symbol == 'AAPL').first()
session.delete(stock)
session.commit()

In the example above, we have retrieved the Stock object for the stock with the symbol value of 'AAPL', and then called the session.delete(stock) method to delete the object from the database. Finally, we have committed the changes to the database by calling the session.commit() method.

Note that when you delete a row from a table, you must always call the session.commit() method to commit the changes to the database. If you do not call the session.commit() method, the deletion will be lost when the session is closed.

In [ ]:

# Query stock

stocks = session.query(Stock.name, Stock.price).all()
for stock in stocks:
    print(stocks)

[('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]
[('Alphabet Inc.', 1100), ('Microsoft Corporation', 200)]

In [ ]:
stocks = session.query( Stock.id,Stock.symbol, Stock.name, Stock.price).limit(10).all()
stocks = session.query( Stock.id,Stock.symbol, Stock.name, Stock.price).filter(
        Stock.price == 200).all()
for stock in stocks:
    print(stocks)

[(3, 'MSFT', 'Microsoft Corporation', 200)]

In [ ]:
# conn = sqlite3.connect('/content/drive/MyDrive/codedose/database.db', timeout=30)
conn = sqlite3.connect('/content/database.db', timeout=30)
c = conn.cursor()

def sq(str,con=conn):
    return pd.read_sql('''{}'''.format(str), con)

tables = sq(
    '''select *
    from sqlite_master
    where type='table';'''
    ,conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,users,users,2,"CREATE TABLE users (id INTEGER PRIMARY KEY, na..."
1,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
2,table,usersDB,usersDB,18,"CREATE TABLE usersDB (id INTEGER PRIMARY KEY, ..."
3,table,Student,Student,19,"CREATE TABLE ""Student"" (\n\t""Id"" INTEGER NOT N..."
4,table,Categories,Categories,3,CREATE TABLE Categories\n( \n Category...
5,table,Customers,Customers,5,CREATE TABLE Customers\n( \n CustomerI...
6,table,Employees,Employees,6,CREATE TABLE Employees\n(\n EmployeeID INTE...
7,table,Shippers,Shippers,7,CREATE TABLE Shippers(\n ShipperID INTEGER ...
8,table,Suppliers,Suppliers,8,CREATE TABLE Suppliers(\n SupplierID INTEGE...
9,table,Products,Products,9,CREATE TABLE Products(\n ProductID INTEGER ...
10,table,Orders,Orders,10,CREATE TABLE Orders(\n OrderID INTEGER PRIM...
11,table,OrderDetails,OrderDetails,11,CREATE TABLE OrderDetails(\n OrderDetailID ...
12,table,stocks,stocks,20,"CREATE TABLE stocks (\n\tid INTEGER NOT NULL, ..."




<a><img src="https://static.wixstatic.com/media/187085_b24573aedefe475989ebd6cbdcbd3e87~mv2.png" width="80%" height="80%" /></a>
source : https://www.apriorit.com/dev-blog/web-python-libraries-for-database-management

It’s important to note that the results of this test may not be representative of every use case. However, this test provides a simple comparison of the performance of each library for a basic insert operation

# ***Note: References***

* https://pyformat.info/
* https://pynative.com/
* https://docs.python.org/3/
* https://www.educba.com/
* https://www.learnbyexample.org/
* https://www.programiz.com/
* http://www.btechsmartclass.com/python/Python_Tutorial_Python_Inheritance.html
* https://pynative.com/python-inheritance/
* https://www.programiz.com/python-programming/object-oriented-programming
* https://realpython.com/python3-object-oriented-programming/#class-and-instance-attributes
* https://ecomputernotes.com/python/file-handling-in-python
* https://www.askpython.com/python/python-file-handling
* https://automatetheboringstuff.com/chapter8/
* https://pynative.com/python-read-file/
* https://docs.python.org/3/library/csv.html
* https://pbpython.com/dataframe-gui-overview.html
* https://realpython.com/pandas-dataframe/
* https://data-flair.training/blogs/pandas-tutorial/
* https://realpython.com/pandas-read-write-files/
* https://www.datacamp.com/tutorial/high-performance-data-manipulation-in-python-pandas2-vs-polars
* https://www.datainsightonline.com/post/how-to-manipulate-data-with-pandas
* https://medium.com/nerd-for-tech/using-csv-data-using-pandas-part-1-138fd3c66d01
* https://www.codecademy.com/learn/data-manipulation-in-python-dvp/modules/pandas-dvp/cheatsheet
* https://www.analyticsvidhya.com/blog/2021/06/data-manipulation-using-pandas-essential-functionalities-of-pandas-you-need-to-know/
* https://www.geeksforgeeks.org/data-manipulattion-in-python-using-pandas/
* https://www.codecademy.com/learn/data-processing-pandas
* https://www.superdatascience.com/courses/data-manipulation-in-python
* https://www.geeksforgeeks.org/creating-a-pandas-dataframe/
* https://pynative.com/python-pandas-dataframe/
* https://medium.com/mlpoint/pandas-for-machine-learning-53846bc9a98b
* https://www.datacamp.com/tutorial/pandas-tutorial-dataframe-python
* https://hossainlab.github.io/pandas/notebooks/01-Getting%20Started.html
* https://class.redclara.net/halley/moncora/Jupyter_Notebooks/apiMakeSens.html
* https://realpython.com/python-sqlite-sqlalchemy/
* https://realpython.com/python-sql-libraries/
* https://en.wikiversity.org/wiki/Database_Examples/Northwind/SQLite
* https://www.sqlitetutorial.net/sqlite-sample-database/
* https://www.kaggle.com/code/alaasedeeq/chinook-sql/notebook
* https://www.datacamp.com/tutorial/sqlalchemy-tutorial-examples
* https://vegibit.com/interacting-with-a-database-using-sqlalchemy-crud-operations/
*